It would help to number each cell/step in the notebook so that it is easy to reference them in various conversations – over email or during the conference presentation.
For cell number #1, I encountered the following error:
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

                So, I would suggest the following change to resolve the above error:

                                $ jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000000 &

I would suggest moving the following step to be run inside the EC2 instance so that we can avoid the upload step of the jupyter notebook from the local laptop to the EC2 instance:

$ git clone https://github.com/aws-samples/reinvent-fine-tune-mxnet-model-for-ios-coreml.git

Typo in cell: Dowload pre-trained model => Download
In cells that take more time, it may help to say: Running this cell may take more than X minutes.
For newbies, it would help to add a line at the top of the notebook, saying:
If you want to run each cell one-by-one, press “Shift-Enter”. The [ ] at the left of the cell will show as [*] while the kernel is running. Wait till the cell execution completes, indicated by [SomeNumber], before you execute the next cell. This will allow you to understand the program in the cell and its output step-by-step.
This import line causes the following failure, because it uses relative and not absolute paths:
import sys
sys.path.append("src/mxnet/tools/coreml")
sys.path.append("src/mxnet/tools/coreml/converter/")
from converter._mxnet_converter import convert
ImportError: No module named converter._mxnet_converter

                I fixed the error by using absolute paths instead of relative paths for the coreml converter directories. Here are the fixed statements:

import sys
sys.path.append("/home/ubuntu/src/mxnet/tools/coreml")
sys.path.append("/home/ubuntu/src/mxnet/tools/coreml/converter/")
from converter._mxnet_converter import convert

Finally, I would recommend adding the following cell as the final cell for a good customer experience with the notebook:

import os.path
if os.path.exists("./coreml.mlmodel"):
    print(":-) CoreML model file saved. Notebook run was SUCCESSFUL!")
else:
    print(":-( CoreML model file was NOT found. Notebook run was NOT SUCCESSFUL.")
    print("Please check the above steps and run them individually")
    print("using Shift-Enter on each cell.")

                With the above steps, the notebook ran fine end-to-end.